package com.learn.jta.bill.mapper;

import com.learn.jta.bill.domain.Bill;
import com.learn.jta.bill.domain.BillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    long countByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    int deleteByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    List<Bill> selectByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bill record, @Param("example") BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    int updateByExample(@Param("record") Bill record, @Param("example") BillExample example);
}