package com.learn.jta.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RepositoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public RepositoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andReNameIsNull() {
			addCriterion("re_name is null");
			return (Criteria) this;
		}

		public Criteria andReNameIsNotNull() {
			addCriterion("re_name is not null");
			return (Criteria) this;
		}

		public Criteria andReNameEqualTo(String value) {
			addCriterion("re_name =", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameNotEqualTo(String value) {
			addCriterion("re_name <>", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameGreaterThan(String value) {
			addCriterion("re_name >", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameGreaterThanOrEqualTo(String value) {
			addCriterion("re_name >=", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameLessThan(String value) {
			addCriterion("re_name <", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameLessThanOrEqualTo(String value) {
			addCriterion("re_name <=", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameLike(String value) {
			addCriterion("re_name like", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameNotLike(String value) {
			addCriterion("re_name not like", value, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameIn(List<String> values) {
			addCriterion("re_name in", values, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameNotIn(List<String> values) {
			addCriterion("re_name not in", values, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameBetween(String value1, String value2) {
			addCriterion("re_name between", value1, value2, "reName");
			return (Criteria) this;
		}

		public Criteria andReNameNotBetween(String value1, String value2) {
			addCriterion("re_name not between", value1, value2, "reName");
			return (Criteria) this;
		}

		public Criteria andStockIsNull() {
			addCriterion("stock is null");
			return (Criteria) this;
		}

		public Criteria andStockIsNotNull() {
			addCriterion("stock is not null");
			return (Criteria) this;
		}

		public Criteria andStockEqualTo(Integer value) {
			addCriterion("stock =", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotEqualTo(Integer value) {
			addCriterion("stock <>", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockGreaterThan(Integer value) {
			addCriterion("stock >", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock >=", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockLessThan(Integer value) {
			addCriterion("stock <", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockLessThanOrEqualTo(Integer value) {
			addCriterion("stock <=", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockIn(List<Integer> values) {
			addCriterion("stock in", values, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotIn(List<Integer> values) {
			addCriterion("stock not in", values, "stock");
			return (Criteria) this;
		}

		public Criteria andStockBetween(Integer value1, Integer value2) {
			addCriterion("stock between", value1, value2, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotBetween(Integer value1, Integer value2) {
			addCriterion("stock not between", value1, value2, "stock");
			return (Criteria) this;
		}

		public Criteria andReLockIsNull() {
			addCriterion("re_lock is null");
			return (Criteria) this;
		}

		public Criteria andReLockIsNotNull() {
			addCriterion("re_lock is not null");
			return (Criteria) this;
		}

		public Criteria andReLockEqualTo(Integer value) {
			addCriterion("re_lock =", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockNotEqualTo(Integer value) {
			addCriterion("re_lock <>", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockGreaterThan(Integer value) {
			addCriterion("re_lock >", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockGreaterThanOrEqualTo(Integer value) {
			addCriterion("re_lock >=", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockLessThan(Integer value) {
			addCriterion("re_lock <", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockLessThanOrEqualTo(Integer value) {
			addCriterion("re_lock <=", value, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockIn(List<Integer> values) {
			addCriterion("re_lock in", values, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockNotIn(List<Integer> values) {
			addCriterion("re_lock not in", values, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockBetween(Integer value1, Integer value2) {
			addCriterion("re_lock between", value1, value2, "reLock");
			return (Criteria) this;
		}

		public Criteria andReLockNotBetween(Integer value1, Integer value2) {
			addCriterion("re_lock not between", value1, value2, "reLock");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNull() {
			addCriterion("gmt_create is null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNotNull() {
			addCriterion("gmt_create is not null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateEqualTo(Date value) {
			addCriterion("gmt_create =", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotEqualTo(Date value) {
			addCriterion("gmt_create <>", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThan(Date value) {
			addCriterion("gmt_create >", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_create >=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThan(Date value) {
			addCriterion("gmt_create <", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
			addCriterion("gmt_create <=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIn(List<Date> values) {
			addCriterion("gmt_create in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotIn(List<Date> values) {
			addCriterion("gmt_create not in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateBetween(Date value1, Date value2) {
			addCriterion("gmt_create between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
			addCriterion("gmt_create not between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNull() {
			addCriterion("gmt_modified is null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNotNull() {
			addCriterion("gmt_modified is not null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedEqualTo(Date value) {
			addCriterion("gmt_modified =", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotEqualTo(Date value) {
			addCriterion("gmt_modified <>", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThan(Date value) {
			addCriterion("gmt_modified >", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_modified >=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThan(Date value) {
			addCriterion("gmt_modified <", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
			addCriterion("gmt_modified <=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIn(List<Date> values) {
			addCriterion("gmt_modified in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotIn(List<Date> values) {
			addCriterion("gmt_modified not in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedBetween(Date value1, Date value2) {
			addCriterion("gmt_modified between", value1, value2, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
			addCriterion("gmt_modified not between", value1, value2, "gmtModified");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table repository
	 * @mbg.generated  Tue Jun 11 23:50:30 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table repository
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 10 21:29:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}