package com.learn.jta.bill.domain;

import java.io.Serializable;
import java.util.Date;

public class Bill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.number
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.status
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.gmt_create
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.gmt_update
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.number
     *
     * @return the value of bill.number
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.number
     *
     * @param number the value for bill.number
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.status
     *
     * @return the value of bill.status
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.status
     *
     * @param status the value for bill.status
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.gmt_create
     *
     * @return the value of bill.gmt_create
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.gmt_create
     *
     * @param gmtCreate the value for bill.gmt_create
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.gmt_update
     *
     * @return the value of bill.gmt_update
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.gmt_update
     *
     * @param gmtUpdate the value for bill.gmt_update
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Mon Jun 10 21:31:17 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", number=").append(number);
        sb.append(", status=").append(status);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}