server:
  port: 7001
spring:
  redis:
    host: 192.168.199.118
    port: 6739
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 5
        max-idle: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.199.118:53306/authority?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
        
mybatis:
  mapper-locations:
  - classpath:com/learn/cloud/authority/mapper/*.xml
logging:
  level:
   com.learn.cloud.authority.*: debug
  
    